### ISSUE TITLE
Long Replies

### ISSUE THREAD

**Issue by DaveenJay** [motianjun4/ChatGPT_Chatbot#1]
Currently, when you ask ChatGPT a long question in the app, it creates a new chat bubble for each paragraph in its response, which causes the previous chat bubbles to be deleted. The desired behavior is for ChatGPT to be able to display multiple paragraphs in a single chat bubble.

Tried using “.lineLimit(nil)” but it didn’t fix the issue.

**Comment by motianjun4** [comment]
Fixed.
